# Generated by Django 5.1.4 on 2025-05-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_expense_options_remove_expense_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='account',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='expenses/'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('OPERATIONAL', 'Operational'), ('SALARY', 'Salary'), ('RENT', 'Rent'), ('UTILITIES', 'Utilities'), ('SHIPPING', 'Shipping'), ('COD', 'COD Charges'), ('MARKETING', 'Marketing'), ('WEBSITE', 'Website'), ('OTHER', 'Other')], default='OPERATIONAL', max_length=20),
        ),
    ]
