# Generated by Django 5.1.4 on 2025-05-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_expense_options_remove_expense_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payable',
            name='expense_type',
            field=models.CharField(choices=[('OPERATIONAL', 'Operational'), ('SALARY', 'Salary'), ('RENT', 'Rent'), ('UTILITIES', 'Utilities'), ('SHIPPING', 'Shipping'), ('COD', 'COD Charges'), ('MARKETING', 'Marketing'), ('WEBSITE', 'Website'), ('OTHER', 'Other')], default='OPERATIONAL', help_text='The type of expense this payable represents', max_length=20),
        ),
    ]
