# Generated by Django 5.1.4 on 2025-05-21 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_payable_expense_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Expense account code (e.g., 5100)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='expense',
            name='type',
        ),
        migrations.RemoveField(
            model_name='payable',
            name='expense_type',
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='accounts.expensecategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='payable',
            name='expense_category',
            field=models.ForeignKey(blank=True, help_text='The category of expense this payable represents', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payables', to='accounts.expensecategory', verbose_name='Expense Category'),
        ),
    ]
