# Generated by Django 5.1.4 on 2025-05-21 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_expensecategory_remove_expense_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='expense_category',
            field=models.ForeignKey(blank=True, help_text='The expense category this account is linked to (for expense accounts only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounts.expensecategory', verbose_name='Expense Category'),
        ),
    ]
