# Generated by Django 5.1.4 on 2025-05-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='category',
            field=models.ManyToManyField(related_name='sub_categories', to='shop.productcategory'),
        ),
    ]
