# Generated by Django 5.1.4 on 2025-05-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productimage_options_productimage_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Sanjilas Shop', max_length=100)),
                ('site_description', models.TextField(blank=True, help_text='Brief description of the website for SEO')),
                ('navbar_logo', models.ImageField(blank=True, help_text='Logo for the navigation bar (recommended size: 200x50px)', upload_to='site_logos/')),
                ('footer_logo', models.ImageField(blank=True, help_text='Logo for the footer (recommended size: 200x50px)', upload_to='site_logos/')),
                ('favicon', models.ImageField(blank=True, help_text='Favicon for the website (recommended size: 32x32px)', upload_to='site_logos/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_address', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for SEO')),
                ('footer_text', models.TextField(blank=True, help_text='Text to display in the footer')),
                ('copyright_text', models.CharField(default='© 2024 Sanjilas Shop. All rights reserved.', max_length=255)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='buying_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
