# Generated by Django 5.1.4 on 2025-05-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_sitesettings_alter_product_buying_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='threads_url',
            field=models.URLField(blank=True, help_text='Threads profile URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube channel or video URL'),
        ),
    ]
