# Generated by Django 5.1.4 on 2025-05-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_sitesettings_google_analytics_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='meta_pixel_id',
            field=models.CharField(blank=True, help_text='Meta Pixel ID (e.g., 644965951111560)', max_length=50),
        ),
    ]
