# Generated by Django 5.1.4 on 2025-05-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_sitesettings_meta_pixel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preorder_delivery_time',
            field=models.CharField(blank=True, default='20-25 days', help_text="Delivery time for preorder products (e.g., '20-25 days')", max_length=100, null=True),
        ),
    ]
