# Generated by Django 5.1.4 on 2025-05-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_aboutus_navigationmenu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavigationMenu',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
