# Generated by Django 5.1.4 on 2025-05-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathaotoken',
            name='access_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pathaotoken',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
