# Generated by Django 5.1.4 on 2025-05-19 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_pathaoarea_zone_and_more'),
        ('shipping', '0002_alter_pathaotoken_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathaoorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pathao_orders', to='order.order'),
        ),
    ]
