# Generated by Django 5.1.4 on 2025-05-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_pathaoorder_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathaocredentials',
            name='webhook_secret',
            field=models.CharField(blank=True, help_text='Secret key for verifying webhook signatures', max_length=255, null=True),
        ),
    ]
