# Generated by Django 5.1.4 on 2025-05-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_pathaocredentials_webhook_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathaocredentials',
            name='webhook_url',
            field=models.CharField(blank=True, help_text='Webhook URL for Pathao', max_length=255, null=True),
        ),
    ]
