# Generated by Django 5.1.4 on 2025-05-18 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathaoArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.IntegerField(help_text='Unique ID of the Pathao area', unique=True)),
                ('area_name', models.CharField(max_length=255)),
                ('home_delivery_available', models.BooleanField(default=False)),
                ('pickup_available', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Pathao Areas',
            },
        ),
        migrations.CreateModel(
            name='PathaoCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField(help_text='Unique ID of the Pathao city', unique=True)),
                ('city_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Pathao Cities',
            },
        ),
        migrations.CreateModel(
            name='PathaoCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(help_text='Pathao API Client ID', max_length=255)),
                ('client_secret', models.CharField(help_text='Pathao API Client Secret', max_length=255)),
                ('default_username', models.CharField(blank=True, help_text='Default username for token issuance', max_length=255, null=True)),
                ('default_password', models.CharField(blank=True, help_text='Default password for token issuance', max_length=255, null=True)),
                ('test_client_id', models.CharField(blank=True, help_text='Pathao Test API Client ID', max_length=255, null=True)),
                ('test_client_secret', models.CharField(blank=True, help_text='Pathao Test API Client Secret', max_length=255, null=True)),
                ('test_username', models.CharField(blank=True, help_text='Test username for token issuance', max_length=255, null=True)),
                ('test_password', models.CharField(blank=True, help_text='Test password for token issuance', max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pathao Credentials',
            },
        ),
        migrations.CreateModel(
            name='PathaoStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField(help_text='Unique ID of the Pathao store', unique=True)),
                ('store_name', models.CharField(max_length=255)),
                ('store_address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('city_id', models.IntegerField()),
                ('zone_id', models.IntegerField()),
                ('hub_id', models.IntegerField(blank=True, null=True)),
                ('is_default_store', models.BooleanField(default=False, help_text='Set as the default store for placing orders')),
            ],
            options={
                'verbose_name_plural': 'Pathao Stores',
            },
        ),
        migrations.CreateModel(
            name='PathaoToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=512)),
                ('refresh_token', models.CharField(blank=True, max_length=512, null=True)),
                ('expires_at', models.DateTimeField(help_text='When the access token expires (timezone aware)')),
            ],
            options={
                'verbose_name_plural': 'Pathao Tokens',
            },
        ),
        migrations.CreateModel(
            name='PathaoZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.IntegerField(help_text='Unique ID of the Pathao zone', unique=True)),
                ('zone_name', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='order.pathaocity')),
            ],
            options={
                'verbose_name_plural': 'Pathao Zones',
            },
        ),
        migrations.CreateModel(
            name='PathaoOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignment_id', models.CharField(blank=True, help_text='Unique ID from Pathao for the consignment', max_length=100, null=True, unique=True)),
                ('merchant_order_id', models.CharField(help_text='Your internal order ID sent to Pathao', max_length=100)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('recipient_address', models.TextField()),
                ('delivery_type', models.IntegerField()),
                ('item_type', models.IntegerField()),
                ('special_instruction', models.TextField(blank=True, null=True)),
                ('item_quantity', models.IntegerField(default=1)),
                ('item_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('amount_to_collect', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_plan_id', models.IntegerField(blank=True, null=True)),
                ('cod_enabled', models.BooleanField(default=False)),
                ('cod_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('additional_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_status', models.CharField(default='Pending', max_length=50)),
                ('order_status_slug', models.CharField(default='Pending', help_text='Slugified status from Pathao', max_length=50)),
                ('pathao_updated_at', models.DateTimeField(blank=True, help_text='Last updated time from Pathao API', null=True)),
                ('invoice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.pathaoarea')),
                ('recipient_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.pathaocity')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.pathaostore')),
                ('recipient_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.pathaozone')),
            ],
            options={
                'verbose_name_plural': 'Pathao Orders',
            },
        ),
        migrations.AddField(
            model_name='pathaoarea',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='order.pathaozone'),
        ),
    ]
