# Generated by Django 5.1.4 on 2025-05-19 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_pathaoarea_pathaocity_pathaocredentials_pathaostore_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathaoarea',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='pathaoorder',
            name='recipient_area',
        ),
        migrations.RemoveField(
            model_name='pathaozone',
            name='city',
        ),
        migrations.RemoveField(
            model_name='pathaoorder',
            name='recipient_city',
        ),
        migrations.DeleteModel(
            name='PathaoCredentials',
        ),
        migrations.RemoveField(
            model_name='pathaoorder',
            name='recipient_zone',
        ),
        migrations.RemoveField(
            model_name='pathaoorder',
            name='store',
        ),
        migrations.DeleteModel(
            name='PathaoToken',
        ),
        migrations.DeleteModel(
            name='PathaoArea',
        ),
        migrations.DeleteModel(
            name='PathaoCity',
        ),
        migrations.DeleteModel(
            name='PathaoZone',
        ),
        migrations.DeleteModel(
            name='PathaoOrder',
        ),
        migrations.DeleteModel(
            name='PathaoStore',
        ),
    ]
