# Generated by Django 5.1.4 on 2025-05-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_pathaoarea_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='area_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='city_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='zone_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
