# Generated by Django 5.1.4 on 2025-05-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='advance_payment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Advance payment received', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount in currency', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage (0-100)', max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_collected',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total payment collected so far', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_due',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remaining payment due', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_history',
            field=models.JSONField(blank=True, default=list, help_text='History of payments made'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_notes',
            field=models.TextField(blank=True, help_text='Notes about payments', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this item', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for this item', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
